// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfumeShop.Models;

#nullable disable

namespace PerfumeShop.Migrations
{
    [DbContext(typeof(PerfumeShopContext))]
    [Migration("20250629135230_kk")]
    partial class kk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerfumeShop.Models.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiDung");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("PerfumeShop.Models.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_NguoiDung")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("PerfumeShop.Models.GioHangChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_GioHang")
                        .HasColumnType("int");

                    b.Property<int>("Id_SanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_GioHang");

                    b.HasIndex("Id_SanPhamChiTiet");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_DiaChi")
                        .HasColumnType("int");

                    b.Property<int?>("Id_MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int>("Id_NguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("Id_PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<int>("Id_PhuongThucVanChuyen")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_DiaChi");

                    b.HasIndex("Id_MaGiamGia");

                    b.HasIndex("Id_NguoiDung");

                    b.HasIndex("Id_PhuongThucThanhToan");

                    b.HasIndex("Id_PhuongThucVanChuyen");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("Id_HoaDon")
                        .HasColumnType("int");

                    b.Property<int>("Id_SanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_HoaDon");

                    b.HasIndex("Id_SanPhamChiTiet");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.MaGiamGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMaGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenMaGiamGia")
                        .IsUnique();

                    b.ToTable("MaGiamGias");
                });

            modelBuilder.Entity("PerfumeShop.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID_TK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ID_TK")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("PerfumeShop.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("PerfumeShop.Models.PhuongThucVanChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiaTien")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucVanChuyens");
                });

            modelBuilder.Entity("PerfumeShop.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("PerfumeShop.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("GiaNhap")
                        .HasColumnType("int");

                    b.Property<int>("Id_SanPham")
                        .HasColumnType("int");

                    b.Property<int>("Id_TheTich")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_SanPham");

                    b.HasIndex("Id_TheTich");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("PerfumeShop.Models.TheTich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TheTichs");
                });

            modelBuilder.Entity("PerfumeShop.Models.DiaChi", b =>
                {
                    b.HasOne("PerfumeShop.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiaChis")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PerfumeShop.Models.GioHang", b =>
                {
                    b.HasOne("PerfumeShop.Models.NguoiDung", "NguoiDung")
                        .WithOne("GioHang")
                        .HasForeignKey("PerfumeShop.Models.GioHang", "Id_NguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PerfumeShop.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("PerfumeShop.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("Id_GioHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("Id_SanPhamChiTiet")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("PerfumeShop.Models.HoaDon", b =>
                {
                    b.HasOne("PerfumeShop.Models.DiaChi", "DiaChi")
                        .WithMany("HoaDons")
                        .HasForeignKey("Id_DiaChi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.MaGiamGia", "MaGiamGia")
                        .WithMany("HoaDons")
                        .HasForeignKey("Id_MaGiamGia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PerfumeShop.Models.NguoiDung", "NguoiDung")
                        .WithMany("HoaDons")
                        .HasForeignKey("Id_NguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("Id_PhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.PhuongThucVanChuyen", "PhuongThucVanChuyen")
                        .WithMany("HoaDons")
                        .HasForeignKey("Id_PhuongThucVanChuyen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiaChi");

                    b.Navigation("MaGiamGia");

                    b.Navigation("NguoiDung");

                    b.Navigation("PhuongThucThanhToan");

                    b.Navigation("PhuongThucVanChuyen");
                });

            modelBuilder.Entity("PerfumeShop.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("PerfumeShop.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("Id_HoaDon")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("Id_SanPhamChiTiet")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("PerfumeShop.Models.NguoiDung", b =>
                {
                    b.HasOne("PerfumeShop.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NguoiDung")
                        .HasForeignKey("PerfumeShop.Models.NguoiDung", "ID_TK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PerfumeShop.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("PerfumeShop.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("Id_SanPham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerfumeShop.Models.TheTich", "TheTich")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("Id_TheTich")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TheTich");
                });

            modelBuilder.Entity("PerfumeShop.Models.DiaChi", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.MaGiamGia", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.NguoiDung", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.PhuongThucVanChuyen", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("PerfumeShop.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("PerfumeShop.Models.TaiKhoan", b =>
                {
                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PerfumeShop.Models.TheTich", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
